language: python
python:
    - 3.6.2
before_install:
  - mkdir dl-files && curl -o dl-files/glove.6B.200d.txt https://file.io/EKobsJ
install:
  - pip install -r server/requirements.txt
script:
  - travis_wait cd server && pytest